jQuery(document).ready(function($){Gritter={fade_speed:2000,timer_stay:6000,_custom_timer:0,_item_count:0,_tpl_close:'<div class="gritter-close"></div>',_tpl_item:'<div id="gritter-item-[[number]]" class="gritter-item-wrapper" style="display:none"><div class="gritter-top"></div><div class="gritter-item"><div class="nottype[[bgcolor]]">[[image]]</div><div class="[[class_name]]"><span class="gritter-title">[[username]]</span><p>[[text]]</p></div><div style="clear:both"></div></div><div class="gritter-bottom"></div></div>',_tpl_wrap:'<div id="gritter-notice-wrapper"></div>',add:function(user,text,image,bgcolor,sticky,time_alive){this.verifyWrapper();var tmp=this._tpl_item;this._item_count++;this._custom_timer=0;if(time_alive){this._custom_timer=time_alive;}
var image_str=(image!='')?'<div class="gritter-ico"><img src="'+image+'" /></div>':'';var class_name=(image!='')?'gritter-with-image':'gritter-without-image';tmp=this.str_replace(['[[username]]','[[text]]','[[image]]','[[bgcolor]]','[[number]]','[[class_name]]'],[user,text,image_str,bgcolor,this._item_count,class_name],tmp);$('#gritter-notice-wrapper').append(tmp);var item=$('#gritter-item-'+this._item_count);var number=this._item_count;item.fadeIn();if(!sticky){this.setFadeTimer(item,number);}
$(item).hover(function(){if(!sticky){Gritter.restoreItemIfFading(this,number);}
Gritter.hoveringItem(this);},function(){if(!sticky){Gritter.setFadeTimer(this,number);}
Gritter.unhoveringItem(this);});return number;},countRemoveWrapper:function(){if($('.gritter-item-wrapper').length==0){$('#gritter-notice-wrapper').remove();}},fade:function(e){$(e).animate({opacity:0},Gritter.fade_speed,function(){$(e).animate({height:0},300,function(){$(e).remove();Gritter.countRemoveWrapper();})})},hoveringItem:function(e){$(e).addClass('hover');if($(e).find('img').length){$(e).find('img').before(this._tpl_close);}
else{$(e).find('span').before(this._tpl_close);}
$(e).find('.gritter-close').click(function(){Gritter.remove(this);});},remove:function(e){$(e).parents('.gritter-item-wrapper').fadeOut('medium',function(){$(this).remove();});this.countRemoveWrapper();$.cookie('showNotice','off',{expires:2});},removeSpecific:function(id,params){var e=$('#gritter-item-'+id);if(typeof(params)==='object'){if(params.fade){var speed=this.fade_speed;if(params.speed){speed=params.speed;}
e.fadeOut(speed);}}
else{e.remove();}
this.countRemoveWrapper();},restoreItemIfFading:function(e,number){window.clearTimeout(Gritter['_int_id_'+number]);$(e).stop().css({opacity:1});},setFadeTimer:function(item,number){var timer_str=(this._custom_timer)?this._custom_timer:this.timer_stay;Gritter['_int_id_'+number]=window.setTimeout(function(){Gritter.fade(item);},timer_str);},stop:function(){$('#gritter-notice-wrapper').fadeOut(function(){$(this).remove();});},str_replace:function(search,replace,subject,count){var i=0,j=0,temp='',repl='',sl=0,fl=0,f=[].concat(search),r=[].concat(replace),s=subject,ra=r instanceof Array,sa=s instanceof Array;s=[].concat(s);if(count){this.window[count]=0;}
for(i=0,sl=s.length;i<sl;i++){if(s[i]===''){continue;}
for(j=0,fl=f.length;j<fl;j++){temp=s[i]+'';repl=ra?(r[j]!==undefined?r[j]:''):r[0];s[i]=(temp).split(f[j]).join(repl);if(count&&s[i]!==temp){this.window[count]+=(temp.length-s[i].length)/f[j].length;}}}
return sa?s:s[0];},unhoveringItem:function(e){$(e).removeClass('hover');$(e).find('.gritter-close').remove();},verifyWrapper:function(){if($('#gritter-notice-wrapper').length==0){$('body').append(this._tpl_wrap);}}}
$.gritter={};$.gritter.add=function(params){try{if(!params.title||!params.text){throw"Missing_Fields";}}catch(e){if(e=="Missing_Fields"){alert('Gritter Error: You need to fill out the first 2 params: "title" and "text"');}}
var id=Gritter.add(params.title,params.text,params.image||'',params.bgcolor||'',params.sticky||false,params.time||'');return id;}
$.gritter.remove=function(id,params){Gritter.removeSpecific(id,params||'');}
$.gritter.removeAll=function(){Gritter.stop();}});